import os
from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy import MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

load_dotenv()

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _resolve(url: str) -> str:
    """Anchor a relative SQLite path to the project root, not the cwd.

    `sqlite:///directory.db` is relative, so it resolves against whatever
    directory the process happens to be started from — and SQLite does not
    error on a missing file, it silently CREATES an empty one. The result is
    that running anything from a subdirectory (`cd eval && python
    run_golden_eval.py`, a seed script, build_search_index.py) produces a
    brand-new empty database and then fails several frames later with
    "no such table: employees", which points at nothing useful.

    Absolute paths (`sqlite:////tmp/x.db`), in-memory databases, and every
    non-SQLite URL are passed through untouched — so the tests' temp-file
    DATABASE_URL and Azure SQL connection strings are unaffected.
    """
    prefix = "sqlite:///"
    if not url.startswith(prefix) or url.startswith("sqlite:////"):
        return url
    path = url[len(prefix):]
    if not path or path.startswith(":memory:"):
        return url
    if Path(path).is_absolute():
        return url
    return f"{prefix}{_PROJECT_ROOT / path}"


DATABASE_URL = _resolve(os.environ.get("DATABASE_URL", "sqlite:///directory.db"))

# Fixed constraint-naming convention so autogenerated migrations produce the
# same constraint names on SQLite and Azure SQL.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    metadata = metadata


connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}
engine = create_engine(DATABASE_URL, connect_args=connect_args)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
