from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.models.enums import ChangeType, ProposedChangeStatus


class ProposedChange(Base):
    """A staging row: one single field-level change the extraction step
    believes a document supports, waiting for a human to agree.

    One row per SKILL, per CONTRIBUTION line, per PROJECT ENTRY — never one
    row per employee or per document. That granularity is what makes
    per-field accept/edit/reject possible: a reviewer can accept that
    someone joined a project while rejecting an overreaching contribution
    sentence about it, without an all-or-nothing bundle forcing the choice.

    The model never writes to EmployeeProject or EmployeeSkill — it emits a
    typed call, that call lands here as `pending`, and only an IT
    reviewer's explicit accept moves content into the real tables (see
    app/proposals.py). Nothing here is searchable or indexed until that
    happens, which is what makes a wrong guess about who "Priya" is a
    review problem rather than a data-integrity one.
    """

    __tablename__ = "proposed_changes"

    # The review queue is always read per-document and filtered by status.
    # Declared here as well as in the migration so `alembic revision
    # --autogenerate` stays silent — an index that exists in the database but
    # not on the model reads as drift and gets "helpfully" dropped by the
    # next autogenerated revision.
    __table_args__ = (
        Index("ix_proposed_changes_doc_status", "source_doc_id", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    # Nullable until the row's doc_subject_matches entry is resolved by a
    # human — see subject_match_id below. This is the field the rest of the
    # app (search, profile reads, reindexing) keys on to decide whether a
    # row belongs to anyone at all; it is never set by the extraction step
    # itself, only by app.proposals.resolve_subject / reassign.
    employee_id: Mapped[str | None] = mapped_column(ForeignKey("employees.id"), nullable=True)

    # Every field-level proposal traces back to the person it's ABOUT, not
    # just the document it came from — extraction attaches rows here at
    # creation time, before anyone knows which employee_id (if any) that
    # resolves to. Nullable only for schema symmetry; in practice every row
    # the pipeline creates has one, immediately. The doc_subject_matches row
    # is what employee_id gets copied from the moment a human resolves it —
    # see app.proposals.resolve_subject.
    subject_match_id: Mapped[int | None] = mapped_column(
        ForeignKey("doc_subject_matches.id"), nullable=True
    )

    source_doc_id: Mapped[int] = mapped_column(ForeignKey("uploaded_docs.id"), nullable=False)

    change_type: Mapped[ChangeType] = mapped_column(
        Enum(ChangeType, native_enum=False, validate_strings=True), nullable=False
    )

    # Both JSON-encoded into Text, matching AuditLog.fields_returned's
    # precedent — neither SQLite nor Azure SQL has a portable native JSON
    # column type, and this project targets both.
    #
    # proposed_value is what would actually be committed on accept, and IS
    # rewritten by /edit and /reassign. original_value is a snapshot of the
    # CURRENT real value at extraction time (null for a field that doesn't
    # exist yet, e.g. a skill the person doesn't hold) — it exists purely so
    # the review screen can render a diff without a second query racing the
    # real row, which could have changed since extraction ran.
    proposed_value: Mapped[str] = mapped_column(Text, nullable=False)
    original_value: Mapped[str | None] = mapped_column(Text, nullable=True)

    # The extraction step's own confidence, 0.0-1.0. Advisory only: it sorts
    # the review queue, and nothing anywhere auto-accepts above a threshold.
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    status: Mapped[ProposedChangeStatus] = mapped_column(
        Enum(ProposedChangeStatus, native_enum=False, validate_strings=True),
        nullable=False, default=ProposedChangeStatus.pending,
    )

    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.now)

    # Not a foreign key, same reason as AuditLog.actor_id — who reviewed this
    # has to outlive their employee row.
    reviewed_by: Mapped[str | None] = mapped_column(String(36), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # JSON-encoded record of exactly what accept()/edit() wrote, captured at
    # commit time — not reconstructed later, which would be guessing at a
    # moving target if another row has since touched the same skill or
    # project membership. This is what app.proposals.undo() reverses; set to
    # None the moment a successful undo runs, and left None forever on rows
    # that predate this column (accept()/edit() only started writing it once
    # undo existed to consume it) — undo() treats that absence as "nothing
    # recorded to reverse," not as a bug.
    undo_state: Mapped[str | None] = mapped_column(Text, nullable=True)

    employee = relationship("Employee")
    source_doc = relationship("UploadedDoc")
    subject_match = relationship("DocSubjectMatch", back_populates="proposed_changes")
