#!/usr/bin/env python3
"""
fetch_secrets.py - Fetch Azure Key Vault secrets and populate local .env file.

Works cross-platform on Windows, macOS, and Linux after performing `az login`.

Usage:
    python fetch_secrets.py
    python fetch_secrets.py --vault-names kv-app-prod-12345
    python fetch_secrets.py --vault-urls https://kv-app-prod-12345.vault.azure.net/
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Check dependencies before running
try:
    from azure.core.exceptions import AzureError
    from azure.identity import DefaultAzureCredential
    from azure.keyvault.secrets import SecretClient
except ImportError:
    print(
        "❌ Missing required Azure dependencies.\n"
        "Please run: pip install azure-identity azure-keyvault-secrets python-dotenv\n"
        "Or: pip install -e '.[backend,dev]'",
        file=sys.stderr,
    )
    sys.exit(1)

# Default vault URLs if none provided via flags or environment
DEFAULT_VAULT_URLS = [
    "https://kv-app-prod-12345.vault.azure.net/",
]


def format_vault_url(name_or_url: str) -> str:
    """Format vault name or URL into a full Azure Key Vault URL."""
    name_or_url = name_or_url.strip()
    if name_or_url.startswith("https://") or name_or_url.startswith("http://"):
        return name_or_url if name_or_url.endswith("/") else f"{name_or_url}/"
    return f"https://{name_or_url}.vault.azure.net/"


def load_existing_env(env_path: Path) -> dict[str, str]:
    """Parse existing .env file into a key-value dict while preserving order."""
    env_vars: dict[str, str] = {}
    if not env_path.exists():
        return env_vars

    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                env_vars[key.strip()] = val.strip()
    return env_vars


def apply_secret_aliases(secrets: dict[str, str]) -> dict[str, str]:
    """Map common key aliases (e.g. SMTP/Gmail, OpenAI) to ensure compatibility across all modules."""
    aliased = dict(secrets)

    # 1. SMTP & Gmail Aliases
    if "SMTP_USER" in aliased and "GOOGLE_EMAIL" not in aliased:
        aliased["GOOGLE_EMAIL"] = aliased["SMTP_USER"]
    elif "GOOGLE_EMAIL" in aliased and "SMTP_USER" not in aliased:
        aliased["SMTP_USER"] = aliased["GOOGLE_EMAIL"]

    if "SMTP_PASSWORD" in aliased and "GOOGLE_APP_PASSWORD" not in aliased:
        aliased["GOOGLE_APP_PASSWORD"] = aliased["SMTP_PASSWORD"]
    elif "GOOGLE_APP_PASSWORD" in aliased and "SMTP_PASSWORD" not in aliased:
        aliased["SMTP_PASSWORD"] = aliased["GOOGLE_APP_PASSWORD"]

    # 2. OpenAI Endpoint & Key Aliases
    if "GROUP1OPENAIENDPOINT" in aliased and "AZURE_OPENAI_ENDPOINT" not in aliased:
        aliased["AZURE_OPENAI_ENDPOINT"] = aliased["GROUP1OPENAIENDPOINT"]
    elif "AZURE_OPENAI_ENDPOINT" in aliased and "GROUP1OPENAIENDPOINT" not in aliased:
        aliased["GROUP1OPENAIENDPOINT"] = aliased["AZURE_OPENAI_ENDPOINT"]

    if "GROUP1OPENAIAPIKEY" in aliased and "AZURE_OPENAI_API_KEY" not in aliased:
        aliased["AZURE_OPENAI_API_KEY"] = aliased["GROUP1OPENAIAPIKEY"]
    elif "AZURE_OPENAI_API_KEY" in aliased and "GROUP1OPENAIAPIKEY" not in aliased:
        aliased["GROUP1OPENAIAPIKEY"] = aliased["AZURE_OPENAI_API_KEY"]

    # 3. Application Insights Connection String Aliases
    app_insights_val = (
        aliased.get("APPLICATIONINSIGHTS_CONNECTION_STRING")
        or aliased.get("APPLICATION_INSIGHTS_CONNECTION_STRING")
        or aliased.get("APPINSIGHTS_CONNECTION_STRING")
        or aliased.get("APP_INSIGHTS_CONNECTION_STRING")
    )
    if app_insights_val:
        aliased["APPLICATIONINSIGHTS_CONNECTION_STRING"] = app_insights_val

    return aliased


def save_env_file(env_path: Path, secrets: dict[str, str]) -> None:
    """Save secret key-value pairs to the local .env file."""
    # Load existing env vars to preserve non-secret local configs
    existing_env = load_existing_env(env_path)

    # Apply secret aliases (e.g. SMTP <-> Google Email, OpenAI aliases)
    updated_secrets = apply_secret_aliases(secrets)
    existing_env.update(updated_secrets)

    lines = [
        "# ==========================================\n",
        "# Auto-generated by fetch_secrets.py\n",
        "# DO NOT commit this file to version control\n",
        "# ==========================================\n\n",
    ]

    for key, value in sorted(existing_env.items()):
        # Escape or quote values if necessary
        if " " in value or "\n" in value or "#" in value or '"' in value:
            clean_val = value.replace('"', '\\"')
            lines.append(f'{key}="{clean_val}"\n')
        else:
            lines.append(f"{key}={value}\n")

    with open(env_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    # On Unix/macOS, set secure file permissions (rw-------)
    if os.name == "posix":
        try:
            os.chmod(env_path, 0o600)
        except OSError:
            pass


def fetch_secrets(vault_urls: list[str], env_path: Path) -> tuple[dict[str, str], int]:
    """Connect to Azure Key Vaults and fetch all secret key-value pairs."""
    print("🔐 Authenticating with Azure CLI credentials...")
    try:
        credential = DefaultAzureCredential()
    except Exception as exc:
        print(f"❌ Failed to instantiate Azure credentials: {exc}", file=sys.stderr)
        print("💡 Ensure you have logged in via: az login", file=sys.stderr)
        sys.exit(1)

    fetched_secrets: dict[str, str] = {}
    vault_count = 0

    for vault_url in vault_urls:
        formatted_url = format_vault_url(vault_url)
        print(f"\n📦 Connecting to Key Vault: {formatted_url}")

        try:
            client = SecretClient(vault_url=formatted_url, credential=credential)
            secret_props = list(client.list_properties_of_secrets())
        except AzureError as err:
            print(
                f"⚠️  Could not connect or list secrets in {formatted_url}.\n"
                f"   Error: {err}\n"
                f"   Check your Azure permissions or run `az login`.",
                file=sys.stderr,
            )
            continue
        except Exception as err:
            print(
                f"⚠️  Unexpected error connecting to {formatted_url}: {err}",
                file=sys.stderr,
            )
            continue

        vault_count += 1
        count = 0
        for prop in secret_props:
            if not prop.enabled:
                continue

            try:
                secret = client.get_secret(prop.name)
                if secret and secret.value is not None:
                    # Convert secret name (e.g. db-admin-password) to env format
                    env_key = prop.name.replace("-", "_").upper()
                    fetched_secrets[env_key] = secret.value
                    count += 1
                    print(f"   ✓ Retrieved secret: {prop.name} -> {env_key}")
            except Exception as err:
                print(
                    f"   ✖ Failed to get value for secret '{prop.name}': {err}",
                    file=sys.stderr,
                )

        print(f"   Fetched {count} secret(s) from {formatted_url}")

    return fetched_secrets, vault_count


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch Azure Key Vault secrets and update local .env file."
    )
    parser.add_argument(
        "--vault-urls",
        nargs="+",
        help="Space-separated list of Azure Key Vault URLs.",
    )
    parser.add_argument(
        "--vault-names",
        nargs="+",
        help="Space-separated list of Azure Key Vault names.",
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to target .env file (default: .env in root directory).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Determine target vault URLs
    vault_urls: list[str] = []
    if args.vault_urls:
        vault_urls.extend(args.vault_urls)
    if args.vault_names:
        vault_urls.extend(args.vault_names)

    # Check environment variable if CLI args not passed
    if not vault_urls and os.environ.get("KEYVAULT_URLS"):
        vault_urls = [
            v.strip() for v in os.environ["KEYVAULT_URLS"].split(",") if v.strip()
        ]

    # Fallback to default project vaults
    if not vault_urls:
        vault_urls = DEFAULT_VAULT_URLS

    target_env_file = Path(args.env_file).resolve()
    print("🚀 Ticket-Genie Remote Secret Fetcher")
    print(f"Target .env file: {target_env_file}")

    secrets, vaults_accessed = fetch_secrets(vault_urls, target_env_file)

    if not secrets:
        print(
            "\n⚠️  No secrets fetched. Local .env file was not modified.\n"
            "💡 Make sure you are logged in (`az login`) and have Key Vault "
            "secrets read access.",
            file=sys.stderr,
        )
        if vaults_accessed == 0:
            sys.exit(1)
        return

    save_env_file(target_env_file, secrets)
    print(
        f"\n✅ Successfully updated {target_env_file} with {len(secrets)} secret(s) "
        f"from {vaults_accessed} Key Vault(s)!"
    )
    print("🔒 Ensure your .env file is added to .gitignore and never committed.")


if __name__ == "__main__":
    main()
