"""Azure Monitor OpenTelemetry Telemetry Setup for FastAPI Backend.

This module handles initializing Azure Application Insights telemetry using the
official Azure Monitor OpenTelemetry Distro (`azure-monitor-opentelemetry`).
"""

import logging
import os
from typing import Optional

from fastapi import FastAPI

logger = logging.getLogger("ticketgenie.telemetry")

_telemetry_initialized = False


def setup_telemetry(app: FastAPI, connection_string: Optional[str] = None) -> bool:
    """Initialize Azure Monitor OpenTelemetry for FastAPI backend.

    Args:
        app: The FastAPI application instance.
        connection_string: Optional explicit connection string. Defaults to
          reading the APPLICATIONINSIGHTS_CONNECTION_STRING environment
          variable.

    Returns:
        bool: True if telemetry was successfully configured, False otherwise.
    """
    global _telemetry_initialized

    if _telemetry_initialized:
        logger.info("[Telemetry Setup] Telemetry already initialized.")
        return True

    raw_conn_str = connection_string or os.getenv(
        "APPLICATIONINSIGHTS_CONNECTION_STRING", ""
    )
    conn_str = raw_conn_str.strip().strip("\"'")

    if not conn_str:
        logger.info(
            "[Telemetry Setup] APPLICATIONINSIGHTS_CONNECTION_STRING not provided. "
            "Telemetry export to Azure Monitor is disabled. (Traces will only log locally)"
        )
        return False

    # Extract masked connection string for safe diagnostic logging
    endpoint_hint = "unknown"
    if "IngestionEndpoint=" in conn_str:
        endpoint_hint = conn_str.split("IngestionEndpoint=")[1].split(";")[0]

    logger.info(
        f"[Telemetry Setup] Found APPLICATIONINSIGHTS_CONNECTION_STRING. "
        f"Configuring Azure Monitor OpenTelemetry (Ingestion: {endpoint_hint})..."
    )

    try:
        from azure.monitor.opentelemetry import configure_azure_monitor
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

        # Configure Azure Monitor OpenTelemetry Distro
        configure_azure_monitor(
            connection_string=conn_str,
            logger_name="ticketgenie",
            enable_live_metrics=True,
        )

        # Ensure logging level is INFO so telemetry records are transmitted
        logging.getLogger("ticketgenie").setLevel(logging.INFO)
        logger.setLevel(logging.INFO)

        # Instrument FastAPI app for route tracing and request metrics
        FastAPIInstrumentor.instrument_app(app)

        _telemetry_initialized = True
        logger.info(
            "[Telemetry Setup] Azure Monitor OpenTelemetry initialized successfully. "
            "All '[LLM Telemetry]' traces will be forwarded to Application Insights."
        )
        return True

    except Exception as exc:
        logger.warning(
            f"[Telemetry Setup] Failed to initialize Azure Monitor telemetry: {exc}",
            exc_info=True,
        )
        return False


# ---------------------------------------------------------------------------
# LLM Token & Cost Telemetry Metrics
# ---------------------------------------------------------------------------

_meter = None
_prompt_tokens_counter = None
_completion_tokens_counter = None
_total_tokens_counter = None
_estimated_cost_counter = None


def get_meter():
    """Get or initialize the OpenTelemetry meter for TicketGenie."""
    global _meter
    global _prompt_tokens_counter
    global _completion_tokens_counter
    global _total_tokens_counter
    global _estimated_cost_counter

    if _meter is None:
        try:
            from opentelemetry import metrics

            _meter = metrics.get_meter("ticketgenie.llm")
            _prompt_tokens_counter = _meter.create_counter(
                name="llm_prompt_tokens",
                description="Total number of prompt tokens used in LLM requests",
                unit="1",
            )
            _completion_tokens_counter = _meter.create_counter(
                name="llm_completion_tokens",
                description="Total number of completion tokens generated by LLM",
                unit="1",
            )
            _total_tokens_counter = _meter.create_counter(
                name="llm_total_tokens",
                description="Total number of tokens consumed across LLM requests",
                unit="1",
            )
            _estimated_cost_counter = _meter.create_counter(
                name="llm_estimated_cost_usd",
                description="Estimated cost in USD for LLM requests",
                unit="USD",
            )
        except Exception as exc:
            logger.warning(f"Could not initialize OpenTelemetry metrics meter: {exc}")
            return None

    return _meter


def record_llm_metrics(
    prompt_tokens: int,
    completion_tokens: int,
    model: str = "gpt-4o",
    agent_name: str = "classifier",
    cached_tokens: int = 0,
) -> None:
    """Record LLM token usage metrics to OpenTelemetry and Azure Monitor.

    Args:
        prompt_tokens: Number of prompt tokens used.
        completion_tokens: Number of completion tokens generated.
        model: Model name/deployment used.
        agent_name: Name of the subagent or service making the call.
        cached_tokens: Number of prompt tokens served from prefix/prompt cache (billed at 50% discount).
    """
    total_tokens = prompt_tokens + completion_tokens
    active_prompt_tokens = max(0, prompt_tokens - cached_tokens)

    # Approximate pricing per 1k tokens (GPT-4o rates: $0.005 prompt, cached prompt $0.0025, $0.015 completion)
    prompt_cost = (active_prompt_tokens / 1000.0) * 0.005 + (
        cached_tokens / 1000.0
    ) * 0.0025
    completion_cost = (completion_tokens / 1000.0) * 0.015
    estimated_cost_usd = round(prompt_cost + completion_cost, 6)

    attributes = {"model": model, "agent": agent_name}

    cache_info = f" cached_tokens={cached_tokens}" if cached_tokens > 0 else ""
    logger.info(
        f"[LLM Telemetry] agent={agent_name} model={model} "
        f"prompt_tokens={prompt_tokens} completion_tokens={completion_tokens} "
        f"total_tokens={total_tokens}{cache_info} est_cost_usd=${estimated_cost_usd:.6f}"
    )

    meter = get_meter()
    if meter and _prompt_tokens_counter:
        try:
            _prompt_tokens_counter.add(prompt_tokens, attributes)
            _completion_tokens_counter.add(completion_tokens, attributes)
            _total_tokens_counter.add(total_tokens, attributes)
            _estimated_cost_counter.add(estimated_cost_usd, attributes)
        except Exception as exc:
            logger.warning(f"Failed to record LLM metrics to OpenTelemetry: {exc}")
