# ==========================================================================
# Auto-Generated Azure Monitor Metric Alerts for OpenAPI Endpoints
# Generated by scripts/generate_openapi_monitoring.py
# ==========================================================================

# 1. Global High Server Error Rate Alert (5xx Errors)
resource "azurerm_monitor_metric_alert" "api_server_errors" {
  name                = "alert-ticketgenie-api-5xx-errors"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers on high HTTP 5xx server errors"
  severity            = 1
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 5
  }
}

# 2. Global High Latency Alert (P95 > 1000ms)
resource "azurerm_monitor_metric_alert" "api_high_latency" {
  name                = "alert-ticketgenie-api-high-latency"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers when average request latency exceeds 1000ms"
  severity            = 2
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/duration"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 1000
  }
}

# 3. HTTP 500 Internal Server Errors Alert
resource "azurerm_monitor_metric_alert" "api_500_errors" {
  name                = "alert-ticketgenie-api-500-errors"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers when HTTP 500 Internal Server Errors occur"
  severity            = 1
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/resultCode"
      operator = "Include"
      values   = ["500"]
    }
  }
}

# 4. HTTP 503 Service Unavailable Errors Alert
resource "azurerm_monitor_metric_alert" "api_503_errors" {
  name                = "alert-ticketgenie-api-503-errors"
  resource_group_name = data.azurerm_resource_group.rg.name
  scopes              = [azurerm_application_insights.appi.id]
  description         = "Triggers when HTTP 503 Service Unavailable errors occur"
  severity            = 1
  frequency           = "PT1M"
  window_size         = "PT5M"

  criteria {
    metric_namespace = "microsoft.insights/components"
    metric_name      = "requests/failed"
    aggregation      = "Count"
    operator         = "GreaterThan"
    threshold        = 3

    dimension {
      name     = "request/resultCode"
      operator = "Include"
      values   = ["503"]
    }
  }
}
