"""prd chatbot requirements and assistant conversations

Revision ID: a54698638eee
Revises: b7d3e0a41c92
Create Date: 2026-08-19 23:46:01.547033

Five operations, one revision, for the PRD chatbot feature:

  project_requirement_notes   new table -- qualitative requirements a PRD
                               (or a person) recorded against a project,
                               kept separate from project_skill_requirements
                               because that table is REPLACE semantics
                               (set_required_skills deletes and re-inserts
                               the full set on every write) -- a nullable-
                               skill row bolted onto it would be silently
                               deleted the next time someone confirms a
                               skill list.
  assistant_conversations,
  assistant_turns             new tables -- server-side persistence for
                               the two chat assistants (search and PRD),
                               storing plans (HistoryTurn's own shape)
                               rather than results, same discipline
                               tool_calling._history_messages() already
                               holds to for in-memory follow-up chat.
  uploaded_docs.project_id    nullable FK -- which project a PRD upload is
                               about. NULL for every other use of this
                               table (status reports, resumes aren't
                               single-project-scoped).
  project_skill_requirements
    .source_doc_id            nullable FK -- which PRD upload declared a
                               skill requirement, if any. Confirmed not to
                               change app/continuity.py's declared-vs-
                               inferred distinction, which is decided by
                               row presence alone, never by a column.

Deliberate consequence: assistant_conversations/assistant_turns exist but
are unused by any application code until the conversation-persistence
phase of this feature ships. That's the price of one revision instead of
two, worth paying given how many alembic head-split merges this repo's
history already has.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54698638eee'
down_revision: Union[str, Sequence[str], None] = 'b7d3e0a41c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assistant_conversations_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_conversations'))
    )
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('assistant_turns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tool_call', sa.String(length=64), nullable=True),
    sa.Column('arguments', sa.Text(), nullable=True),
    sa.Column('assistant_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], name=op.f('fk_assistant_turns_conversation_id_assistant_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_turns'))
    )
    with op.batch_alter_table('assistant_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_turns_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('project_requirement_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_requirement_notes_project_id_projects')),
    sa.ForeignKeyConstraint(['source_doc_id'], ['uploaded_docs.id'], name=op.f('fk_project_requirement_notes_source_doc_id_uploaded_docs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_requirement_notes'))
    )
    # NOTE: autogenerate also proposed two alter_column ops on
    # employee_action_requests (action_type/status VARCHAR -> Enum) --
    # removed. Nothing in this revision touches that table; it's a known
    # autogenerate false positive comparing a SQLAlchemy Enum(native_enum=
    # False) column against the plain VARCHAR the historical migration
    # chain built it as, with no functional difference.
    with op.batch_alter_table('project_skill_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_doc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project_skill_requirements_source_doc_id_uploaded_docs'), 'uploaded_docs', ['source_doc_id'], ['id'])

    with op.batch_alter_table('uploaded_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_uploaded_docs_project_id_projects'), 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_docs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uploaded_docs_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project_skill_requirements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project_skill_requirements_source_doc_id_uploaded_docs'), type_='foreignkey')
        batch_op.drop_column('source_doc_id')

    op.drop_table('project_requirement_notes')
    with op.batch_alter_table('assistant_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_turns_conversation_id'))

    op.drop_table('assistant_turns')
    with op.batch_alter_table('assistant_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_conversations_user_id'))

    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
