"""backfill real project descriptions

Revision ID: abb9a2a3ab1e
Revises: 988e51b2d49c
Create Date: 2026-08-14

A DATA migration, same justification as 6886efd9b63d (the training
catalogue seed): the deployed database is only reachable from inside
Azure's network boundary, and the App Service already runs
`alembic upgrade head` at startup, so this is the one channel that reaches
it without an interactive session on the container.

ARCHITECTURE_2.md §11: 114 of the original 118 project descriptions (now
126 of 129, after later growth) were the literal template
f"{name} — owned by {dept}." — median 58 characters, no semantic content to
embed, which makes mode 3 (semantic search over project vectors) just
name-matching with an embedding round-trip bolted on. seed.py and
seed_continuity.py now generate real 2-4 sentence descriptions (problem,
tech, what went wrong) for every project going forward; this migration
backfills the ones that already exist in a database seeded before that
change — local directory.db and, more importantly, the deployed database,
which a migration is the only way to reach.

Each row is only updated if its CURRENT description still matches the old
template-generated text exactly. That makes this idempotent by inspection
(a second run finds nothing left to match) and safe against a database
where a description was already hand-edited away from the template for
some other reason — this migration only ever overwrites its own known
prior text, never a description it doesn't recognize.

Run `python build_search_index.py` afterwards against whichever database
this ran on — same as any other project-data change, the search index is
a snapshot and won't pick up new description text on its own.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abb9a2a3ab1e"
down_revision: Union[str, Sequence[str], None] = "988e51b2d49c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DESCRIPTIONS = [
    ('Employee Directory Platform', 'Employee Directory Platform — owned by Platform Engineering.', "The internal system of record for who works where, replacing three years of drift across spreadsheets, a stale Confluence wiki, and word of mouth. Search, org charts, and skills all read from one API instead of being manually reconciled by hand. The original launch undercounted contractors because the HRIS feed didn't distinguish employment type, which took two sprints to unwind after go-live."),
    ('Billing API', 'Billing API — owned by Platform Engineering.', "Consolidates invoicing and usage metering for every product line behind one versioned API, replacing per-product billing logic that had quietly diverged over several years of feature work. Idempotent webhook delivery means a retried event can't double-charge a customer. The initial rollout under-provisioned for spiky end-of-month invoice runs and needed a follow-up scaling pass within the first quarter."),
    ('Payroll Processing System', 'Payroll Processing System — owned by Payroll.', "Handles salary calculation, tax withholding, and disbursement for the full employee population, integrating with the payroll provider's API rather than re-implementing tax logic in house. Maintained by a small, tightly-scoped team given the sensitivity of the data it touches. An early version miscalculated withholding for employees who changed states mid-year, caught in the first quarterly audit."),
    ('Project Nightingale', 'Project Nightingale — owned by Engineering.', "A confidential initiative scoped directly under Engineering leadership, evaluating a potential acquisition target's technical stack for integration risk. A small, need-to-know team performs due diligence on the target's codebase, infrastructure, and data practices. The engagement uncovered enough undocumented legacy dependencies that the integration timeline slipped by a full quarter."),
    ('ML Personalization Engine', 'ML Personalization Engine — owned by Data & AI.', "Ranks and personalizes in-product recommendations using a model trained on clickstream and account-tier data, replacing a static rules engine that hadn't been touched in two years. Evaluated offline against held-out click data before each rollout. The first production model overfit to power users and had to be retrained with better sampling to serve the long tail fairly."),
    ('Customer Data Retention Policy', 'Customer Data Retention Policy — owned by Compliance.', "Defines how long customer data is retained across every system after an account closes, and the automated deletion jobs that enforce it, replacing an ad hoc mix of manual deletion requests and indefinite retention. Written to satisfy GDPR's storage-limitation principle and reviewed jointly with Engineering to confirm every downstream system actually honors the schedule. The first draft missed backup retention entirely, which the external audit flagged before publication."),
    ('SOC 2 Compliance Program', 'SOC 2 Compliance Program — owned by Compliance.', "The ongoing control framework and evidence collection process behind the company's annual SOC 2 Type II audit, covering access reviews, change management, and incident response. Runs on a mix of manual quarterly attestations and automated log collection from the core platform. The first audit cycle surfaced gaps in offboarding timeliness that took a dedicated remediation sprint to close."),
    ('Talent Acquisition Function', 'Talent Acquisition Function — owned by Talent Acquisition.', 'The end-to-end hiring pipeline from requisition approval through offer, standardized across departments after each team had been running its own ad hoc process. Uses an applicant tracking system integrated with structured interview scorecards to reduce variance between interviewers. Time-to-fill improved, but scorecard adoption stayed uneven until interviewer training became mandatory.'),
    ('Global Mobility Policy', 'Global Mobility Policy — owned by HR Operations.', "Governs visa sponsorship, relocation support, and cross-border transfers for employees moving between offices, replacing a patchwork of country-specific exceptions handled case by case. Coordinated with outside immigration counsel to keep the policy current against each jurisdiction's changing rules. An early version didn't account for dependent visas, which delayed several approved transfers until it was amended."),
    ('Enterprise Sales Playbook', 'Enterprise Sales Playbook — owned by Sales.', 'The standardized methodology, objection-handling guide, and deal-desk process for enterprise accounts, built after inconsistent discounting and messaging across the sales team started showing up in win-rate data. Grounded in pipeline data and a common qualification framework. Adoption lagged for two quarters until it was tied directly to deal-desk approval instead of just training.'),
    ('Platform Engineering Process Improvement Initiative', 'Platform Engineering Process Improvement Initiative — owned by Platform Engineering.', "A working effort to cut the time Platform Engineering spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Python to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Platform Engineering Tooling Upgrade', 'Platform Engineering Tooling Upgrade — owned by Platform Engineering.', "Replaces the aging toolchain Platform Engineering had outgrown with a stack built around Python and JavaScript, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Platform Engineering Onboarding Revamp', 'Platform Engineering Onboarding Revamp — owned by Platform Engineering.', "Redesigns how a new hire in Platform Engineering ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Python curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Platform Engineering Vendor Consolidation', 'Platform Engineering Vendor Consolidation — owned by Platform Engineering.', "Reduces Platform Engineering's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Python workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Platform Engineering Reporting Overhaul', 'Platform Engineering Reporting Overhaul — owned by Platform Engineering.', "Replaces Platform Engineering's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Python, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Platform Engineering Workflow Automation', 'Platform Engineering Workflow Automation — owned by Platform Engineering.', "Automates a workflow inside Platform Engineering that previously required someone to manually shepherd a request through several handoffs, using Python to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Platform Engineering Knowledge Base Migration', 'Platform Engineering Knowledge Base Migration — owned by Platform Engineering.', "Moves Platform Engineering's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Python experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Platform Engineering Annual Planning Cycle', 'Platform Engineering Annual Planning Cycle — owned by Platform Engineering.', "The recurring process Platform Engineering uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Python so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Data & AI Process Improvement Initiative', 'Data & AI Process Improvement Initiative — owned by Data & AI.', "A working effort to cut the time Data & AI spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Python to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Data & AI Tooling Upgrade', 'Data & AI Tooling Upgrade — owned by Data & AI.', "Replaces the aging toolchain Data & AI had outgrown with a stack built around Python and SQL, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Data & AI Onboarding Revamp', 'Data & AI Onboarding Revamp — owned by Data & AI.', "Redesigns how a new hire in Data & AI ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Python curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Data & AI Vendor Consolidation', 'Data & AI Vendor Consolidation — owned by Data & AI.', "Reduces Data & AI's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Python workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Data & AI Reporting Overhaul', 'Data & AI Reporting Overhaul — owned by Data & AI.', "Replaces Data & AI's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Python, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Data & AI Workflow Automation', 'Data & AI Workflow Automation — owned by Data & AI.', "Automates a workflow inside Data & AI that previously required someone to manually shepherd a request through several handoffs, using Python to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Data & AI Knowledge Base Migration', 'Data & AI Knowledge Base Migration — owned by Data & AI.', "Moves Data & AI's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Python experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Data & AI Annual Planning Cycle', 'Data & AI Annual Planning Cycle — owned by Data & AI.', "The recurring process Data & AI uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Python so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Infrastructure Process Improvement Initiative', 'Infrastructure Process Improvement Initiative — owned by Infrastructure.', "A working effort to cut the time Infrastructure spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on AWS to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Infrastructure Tooling Upgrade', 'Infrastructure Tooling Upgrade — owned by Infrastructure.', "Replaces the aging toolchain Infrastructure had outgrown with a stack built around AWS and Azure, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Infrastructure Onboarding Revamp', 'Infrastructure Onboarding Revamp — owned by Infrastructure.', "Redesigns how a new hire in Infrastructure ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured AWS curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Infrastructure Vendor Consolidation', 'Infrastructure Vendor Consolidation — owned by Infrastructure.', "Reduces Infrastructure's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing AWS workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Infrastructure Reporting Overhaul', 'Infrastructure Reporting Overhaul — owned by Infrastructure.', "Replaces Infrastructure's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around AWS, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Infrastructure Workflow Automation', 'Infrastructure Workflow Automation — owned by Infrastructure.', "Automates a workflow inside Infrastructure that previously required someone to manually shepherd a request through several handoffs, using AWS to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Infrastructure Knowledge Base Migration', 'Infrastructure Knowledge Base Migration — owned by Infrastructure.', "Moves Infrastructure's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on AWS experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Infrastructure Annual Planning Cycle', 'Infrastructure Annual Planning Cycle — owned by Infrastructure.', "The recurring process Infrastructure uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using AWS so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Quality Engineering Process Improvement Initiative', 'Quality Engineering Process Improvement Initiative — owned by Quality Engineering.', "A working effort to cut the time Quality Engineering spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Python to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Quality Engineering Tooling Upgrade', 'Quality Engineering Tooling Upgrade — owned by Quality Engineering.', "Replaces the aging toolchain Quality Engineering had outgrown with a stack built around Python and Java, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Quality Engineering Onboarding Revamp', 'Quality Engineering Onboarding Revamp — owned by Quality Engineering.', "Redesigns how a new hire in Quality Engineering ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Python curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Quality Engineering Vendor Consolidation', 'Quality Engineering Vendor Consolidation — owned by Quality Engineering.', "Reduces Quality Engineering's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Python workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Quality Engineering Reporting Overhaul', 'Quality Engineering Reporting Overhaul — owned by Quality Engineering.', "Replaces Quality Engineering's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Python, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Quality Engineering Workflow Automation', 'Quality Engineering Workflow Automation — owned by Quality Engineering.', "Automates a workflow inside Quality Engineering that previously required someone to manually shepherd a request through several handoffs, using Python to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Quality Engineering Knowledge Base Migration', 'Quality Engineering Knowledge Base Migration — owned by Quality Engineering.', "Moves Quality Engineering's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Python experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Quality Engineering Annual Planning Cycle', 'Quality Engineering Annual Planning Cycle — owned by Quality Engineering.', "The recurring process Quality Engineering uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Python so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Product Management Process Improvement Initiative', 'Product Management Process Improvement Initiative — owned by Product Management.', "A working effort to cut the time Product Management spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Product Analytics to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Product Management Tooling Upgrade', 'Product Management Tooling Upgrade — owned by Product Management.', "Replaces the aging toolchain Product Management had outgrown with a stack built around Product Analytics and Agile/Scrum, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Product Management Onboarding Revamp', 'Product Management Onboarding Revamp — owned by Product Management.', "Redesigns how a new hire in Product Management ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Product Analytics curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Product Management Vendor Consolidation', 'Product Management Vendor Consolidation — owned by Product Management.', "Reduces Product Management's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Product Analytics workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Product Management Reporting Overhaul', 'Product Management Reporting Overhaul — owned by Product Management.', "Replaces Product Management's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Product Analytics, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Product Management Workflow Automation', 'Product Management Workflow Automation — owned by Product Management.', "Automates a workflow inside Product Management that previously required someone to manually shepherd a request through several handoffs, using Product Analytics to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Product Management Knowledge Base Migration', 'Product Management Knowledge Base Migration — owned by Product Management.', "Moves Product Management's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Product Analytics experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Product Management Annual Planning Cycle', 'Product Management Annual Planning Cycle — owned by Product Management.', "The recurring process Product Management uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Product Analytics so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Design Process Improvement Initiative', 'Design Process Improvement Initiative — owned by Design.', "A working effort to cut the time Design spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Figma to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Design Tooling Upgrade', 'Design Tooling Upgrade — owned by Design.', "Replaces the aging toolchain Design had outgrown with a stack built around Figma and UX Research, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Design Onboarding Revamp', 'Design Onboarding Revamp — owned by Design.', "Redesigns how a new hire in Design ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Figma curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Design Vendor Consolidation', 'Design Vendor Consolidation — owned by Design.', "Reduces Design's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Figma workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Design Reporting Overhaul', 'Design Reporting Overhaul — owned by Design.', "Replaces Design's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Figma, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Design Workflow Automation', 'Design Workflow Automation — owned by Design.', "Automates a workflow inside Design that previously required someone to manually shepherd a request through several handoffs, using Figma to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Design Knowledge Base Migration', 'Design Knowledge Base Migration — owned by Design.', "Moves Design's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Figma experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Design Annual Planning Cycle', 'Design Annual Planning Cycle — owned by Design.', "The recurring process Design uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Figma so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Sales Process Improvement Initiative', 'Sales Process Improvement Initiative — owned by Sales.', "A working effort to cut the time Sales spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Salesforce to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Sales Tooling Upgrade', 'Sales Tooling Upgrade — owned by Sales.', "Replaces the aging toolchain Sales had outgrown with a stack built around Salesforce and Contract Negotiation, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Sales Onboarding Revamp', 'Sales Onboarding Revamp — owned by Sales.', "Redesigns how a new hire in Sales ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Salesforce curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Sales Vendor Consolidation', 'Sales Vendor Consolidation — owned by Sales.', "Reduces Sales's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Salesforce workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Sales Reporting Overhaul', 'Sales Reporting Overhaul — owned by Sales.', "Replaces Sales's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Salesforce, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Sales Workflow Automation', 'Sales Workflow Automation — owned by Sales.', "Automates a workflow inside Sales that previously required someone to manually shepherd a request through several handoffs, using Salesforce to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Sales Knowledge Base Migration', 'Sales Knowledge Base Migration — owned by Sales.', "Moves Sales's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Salesforce experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Sales Annual Planning Cycle', 'Sales Annual Planning Cycle — owned by Sales.', "The recurring process Sales uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Salesforce so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Marketing Process Improvement Initiative', 'Marketing Process Improvement Initiative — owned by Marketing.', "A working effort to cut the time Marketing spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on HubSpot to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Marketing Tooling Upgrade', 'Marketing Tooling Upgrade — owned by Marketing.', "Replaces the aging toolchain Marketing had outgrown with a stack built around HubSpot and SEO, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Marketing Onboarding Revamp', 'Marketing Onboarding Revamp — owned by Marketing.', "Redesigns how a new hire in Marketing ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured HubSpot curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Marketing Vendor Consolidation', 'Marketing Vendor Consolidation — owned by Marketing.', "Reduces Marketing's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing HubSpot workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Marketing Reporting Overhaul', 'Marketing Reporting Overhaul — owned by Marketing.', "Replaces Marketing's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around HubSpot, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Marketing Workflow Automation', 'Marketing Workflow Automation — owned by Marketing.', "Automates a workflow inside Marketing that previously required someone to manually shepherd a request through several handoffs, using HubSpot to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Marketing Knowledge Base Migration', 'Marketing Knowledge Base Migration — owned by Marketing.', "Moves Marketing's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on HubSpot experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Marketing Annual Planning Cycle', 'Marketing Annual Planning Cycle — owned by Marketing.', "The recurring process Marketing uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using HubSpot so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Finance Operations Process Improvement Initiative', 'Finance Operations Process Improvement Initiative — owned by Finance Operations.', "A working effort to cut the time Finance Operations spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Advanced Excel to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Finance Operations Tooling Upgrade', 'Finance Operations Tooling Upgrade — owned by Finance Operations.', "Replaces the aging toolchain Finance Operations had outgrown with a stack built around Advanced Excel and Financial Modeling, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Finance Operations Onboarding Revamp', 'Finance Operations Onboarding Revamp — owned by Finance Operations.', "Redesigns how a new hire in Finance Operations ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Advanced Excel curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Finance Operations Vendor Consolidation', 'Finance Operations Vendor Consolidation — owned by Finance Operations.', "Reduces Finance Operations's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Advanced Excel workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Finance Operations Reporting Overhaul', 'Finance Operations Reporting Overhaul — owned by Finance Operations.', "Replaces Finance Operations's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Advanced Excel, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Finance Operations Workflow Automation', 'Finance Operations Workflow Automation — owned by Finance Operations.', "Automates a workflow inside Finance Operations that previously required someone to manually shepherd a request through several handoffs, using Advanced Excel to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Finance Operations Knowledge Base Migration', 'Finance Operations Knowledge Base Migration — owned by Finance Operations.', "Moves Finance Operations's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Advanced Excel experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Finance Operations Annual Planning Cycle', 'Finance Operations Annual Planning Cycle — owned by Finance Operations.', "The recurring process Finance Operations uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Advanced Excel so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Payroll Process Improvement Initiative', 'Payroll Process Improvement Initiative — owned by Payroll.', "A working effort to cut the time Payroll spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Payroll Systems to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Payroll Tooling Upgrade', 'Payroll Tooling Upgrade — owned by Payroll.', "Replaces the aging toolchain Payroll had outgrown with a stack built around Payroll Systems and Advanced Excel, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Payroll Onboarding Revamp', 'Payroll Onboarding Revamp — owned by Payroll.', "Redesigns how a new hire in Payroll ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Payroll Systems curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Payroll Vendor Consolidation', 'Payroll Vendor Consolidation — owned by Payroll.', "Reduces Payroll's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Payroll Systems workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Payroll Reporting Overhaul', 'Payroll Reporting Overhaul — owned by Payroll.', "Replaces Payroll's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Payroll Systems, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Payroll Workflow Automation', 'Payroll Workflow Automation — owned by Payroll.', "Automates a workflow inside Payroll that previously required someone to manually shepherd a request through several handoffs, using Payroll Systems to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Payroll Knowledge Base Migration', 'Payroll Knowledge Base Migration — owned by Payroll.', "Moves Payroll's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Payroll Systems experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Payroll Annual Planning Cycle', 'Payroll Annual Planning Cycle — owned by Payroll.', "The recurring process Payroll uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Payroll Systems so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('HR Operations Process Improvement Initiative', 'HR Operations Process Improvement Initiative — owned by HR Operations.', "A working effort to cut the time HR Operations spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Employment Law to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('HR Operations Tooling Upgrade', 'HR Operations Tooling Upgrade — owned by HR Operations.', "Replaces the aging toolchain HR Operations had outgrown with a stack built around Employment Law and Change Management, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('HR Operations Onboarding Revamp', 'HR Operations Onboarding Revamp — owned by HR Operations.', "Redesigns how a new hire in HR Operations ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Employment Law curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('HR Operations Vendor Consolidation', 'HR Operations Vendor Consolidation — owned by HR Operations.', "Reduces HR Operations's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Employment Law workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('HR Operations Reporting Overhaul', 'HR Operations Reporting Overhaul — owned by HR Operations.', "Replaces HR Operations's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Employment Law, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('HR Operations Workflow Automation', 'HR Operations Workflow Automation — owned by HR Operations.', "Automates a workflow inside HR Operations that previously required someone to manually shepherd a request through several handoffs, using Employment Law to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('HR Operations Knowledge Base Migration', 'HR Operations Knowledge Base Migration — owned by HR Operations.', "Moves HR Operations's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Employment Law experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('HR Operations Annual Planning Cycle', 'HR Operations Annual Planning Cycle — owned by HR Operations.', "The recurring process HR Operations uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Employment Law so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Talent Acquisition Process Improvement Initiative', 'Talent Acquisition Process Improvement Initiative — owned by Talent Acquisition.', "A working effort to cut the time Talent Acquisition spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Applicant Tracking Systems to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Talent Acquisition Tooling Upgrade', 'Talent Acquisition Tooling Upgrade — owned by Talent Acquisition.', "Replaces the aging toolchain Talent Acquisition had outgrown with a stack built around Applicant Tracking Systems and Employment Law, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Talent Acquisition Onboarding Revamp', 'Talent Acquisition Onboarding Revamp — owned by Talent Acquisition.', "Redesigns how a new hire in Talent Acquisition ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Applicant Tracking Systems curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Talent Acquisition Vendor Consolidation', 'Talent Acquisition Vendor Consolidation — owned by Talent Acquisition.', "Reduces Talent Acquisition's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Applicant Tracking Systems workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Talent Acquisition Reporting Overhaul', 'Talent Acquisition Reporting Overhaul — owned by Talent Acquisition.', "Replaces Talent Acquisition's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Applicant Tracking Systems, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Talent Acquisition Workflow Automation', 'Talent Acquisition Workflow Automation — owned by Talent Acquisition.', "Automates a workflow inside Talent Acquisition that previously required someone to manually shepherd a request through several handoffs, using Applicant Tracking Systems to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Talent Acquisition Knowledge Base Migration', 'Talent Acquisition Knowledge Base Migration — owned by Talent Acquisition.', "Moves Talent Acquisition's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Applicant Tracking Systems experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Talent Acquisition Annual Planning Cycle', 'Talent Acquisition Annual Planning Cycle — owned by Talent Acquisition.', "The recurring process Talent Acquisition uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Applicant Tracking Systems so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Compliance Process Improvement Initiative', 'Compliance Process Improvement Initiative — owned by Compliance.', "A working effort to cut the time Compliance spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Employment Law to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('Compliance Tooling Upgrade', 'Compliance Tooling Upgrade — owned by Compliance.', "Replaces the aging toolchain Compliance had outgrown with a stack built around Employment Law and GDPR, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('Compliance Onboarding Revamp', 'Compliance Onboarding Revamp — owned by Compliance.', "Redesigns how a new hire in Compliance ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Employment Law curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('Compliance Vendor Consolidation', 'Compliance Vendor Consolidation — owned by Compliance.', "Reduces Compliance's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Employment Law workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('Compliance Reporting Overhaul', 'Compliance Reporting Overhaul — owned by Compliance.', "Replaces Compliance's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Employment Law, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('Compliance Workflow Automation', 'Compliance Workflow Automation — owned by Compliance.', "Automates a workflow inside Compliance that previously required someone to manually shepherd a request through several handoffs, using Employment Law to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('Compliance Knowledge Base Migration', 'Compliance Knowledge Base Migration — owned by Compliance.', "Moves Compliance's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Employment Law experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('Compliance Annual Planning Cycle', 'Compliance Annual Planning Cycle — owned by Compliance.', "The recurring process Compliance uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Employment Law so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('IT Operations Process Improvement Initiative', 'IT Operations Process Improvement Initiative — owned by IT Operations.', "A working effort to cut the time IT Operations spends on its most repetitive recurring process, after headcount growth made the old ad hoc approach unsustainable. The team leaned on Network Administration to document and standardize steps that had previously lived in a few people's heads. Measured cycle time improved, but adoption outside the pilot group lagged until the new process became the default rather than an alternative."),
    ('IT Operations Tooling Upgrade', 'IT Operations Tooling Upgrade — owned by IT Operations.', "Replaces the aging toolchain IT Operations had outgrown with a stack built around Network Administration and Cybersecurity, chosen after the old tools stopped scaling with the team's headcount. Migration ran in parallel with day-to-day work rather than a hard cutover. A subset of historical records didn't map cleanly to the new schema and needed manual reconciliation after go-live."),
    ('IT Operations Onboarding Revamp', 'IT Operations Onboarding Revamp — owned by IT Operations.', "Redesigns how a new hire in IT Operations ramps up in their first 90 days, after exit interviews kept naming a confusing, undocumented ramp-up as a top complaint. The new program pairs a structured Network Administration curriculum with a named buddy for the first month instead of leaving new hires to piece it together informally. Early cohorts ramped faster, though the buddy step was inconsistently followed until it was added to the buddy's own goals."),
    ('IT Operations Vendor Consolidation', 'IT Operations Vendor Consolidation — owned by IT Operations.', "Reduces IT Operations's sprawl of overlapping vendor contracts down to a shortlist chosen for actual usage rather than legacy habit, after a spend review found licenses paid for tools nobody had opened in months. The evaluation weighted integration with the team's existing Network Administration workflow alongside price. One migrated workflow broke silently for several weeks because the new vendor's API behaved differently under load than the sales demo had suggested."),
    ('IT Operations Reporting Overhaul', 'IT Operations Reporting Overhaul — owned by IT Operations.', "Replaces IT Operations's manually assembled monthly reporting deck with a live dashboard pulling directly from source systems, after recurring discrepancies between the deck and the underlying data eroded trust in the numbers. Built around Network Administration, with a single agreed definition for every metric that previously had two or three quietly different versions floating around. The first version was too slow to load with a full quarter of history, which needed a follow-up pass on the underlying queries."),
    ('IT Operations Workflow Automation', 'IT Operations Workflow Automation — owned by IT Operations.', "Automates a workflow inside IT Operations that previously required someone to manually shepherd a request through several handoffs, using Network Administration to trigger the next step automatically instead of waiting on someone to notice an email. Turnaround time improved noticeably once live. The automation didn't originally handle the exception path for rejected requests, which routed silently nowhere until a teammate happened to notice a backlog."),
    ('IT Operations Knowledge Base Migration', 'IT Operations Knowledge Base Migration — owned by IT Operations.', "Moves IT Operations's documentation off a wiki that had become unsearchable after years of copy-pasted pages into a structured knowledge base with actual ownership per article. Content review leaned on people with hands-on Network Administration experience to flag what was still accurate versus quietly outdated. A meaningful chunk of pages turned out to describe a process the team had already stopped using, and got archived rather than migrated."),
    ('IT Operations Annual Planning Cycle', 'IT Operations Annual Planning Cycle — owned by IT Operations.', "The recurring process IT Operations uses to set priorities and headcount asks for the year ahead, run each cycle against the previous year's actuals rather than from a blank page. Planning inputs are pulled together using Network Administration so every team submits comparable numbers instead of a mix of formats. The first cycle run this way still slipped past its deadline because two teams' inputs depended on a third team's numbers that weren't ready yet."),
    ('Company All-Hands Modernization', 'Company All-Hands Modernization — company-wide.', 'Redesigns the monthly company all-hands after employee survey feedback consistently rated it a one-way broadcast not worth attending live. Adds a structured Q&A segment and pre-submitted questions instead of an open mic a handful of people dominated. Attendance improved, but the pre-submission window is still short enough that some questions arrive too late to prep a real answer.'),
    ('Leadership Offsite Planning', 'Leadership Offsite Planning — company-wide.', "The annual process for scoping, budgeting, and running the leadership offsite, standardized after a previous year's offsite went noticeably over budget with no clear owner for the overrun. Centralizes venue, travel, and agenda planning under one accountable owner instead of splitting it across whoever volunteered. Agenda planning still tends to start later than the budget does, which compresses prep time for facilitators."),
    ('Annual Strategy Refresh', 'Annual Strategy Refresh — company-wide.', "The yearly process for revisiting company strategy against the prior year's actual results, rather than treating the previous plan as fixed. Each division head brings a one-page summary of what changed in their world, reviewed together before company-wide priorities are finalized. The first cycle under this format ran long because divisions hadn't agreed in advance on how much detail belonged in the one-pager."),
    ('Cross-Functional Culture Initiative', 'Cross-Functional Culture Initiative — company-wide.', 'A company-wide effort to strengthen collaboration between departments that historically operated in isolation, after an internal survey flagged interdepartmental friction as a recurring theme. Introduced regular cross-team shadowing and a shared internal newsletter highlighting work from other departments. Participation was strong at launch but tapered once the initial novelty wore off, prompting a mid-year refresh of the format.'),
    ('Meridian Health — Claims Platform Modernization', 'Meridian Health — Claims Platform Modernization — client engagement.', "Migrating a healthcare claims processor off a legacy claims engine onto a modern, API-driven platform, with HIPAA compliance and audit trails as hard requirements throughout. Cutover is phased by claim type rather than a single big-bang migration, to keep any one failure's blast radius small. Early testing surfaced a discrepancy in how the legacy system rounded partial-dollar claim adjustments, which needed sign-off from the client's compliance team before the new logic could ship."),
    ('Solstice Retail — POS Integration Programme', 'Solstice Retail — POS Integration Programme — client engagement.', "Integrating a national retail chain's point-of-sale terminals with a new inventory and loyalty backend, replacing a batch nightly sync that left store-level stock counts stale for up to a day. Rollout is staged store-by-store so a bad release only affects a handful of locations at a time. A subset of older terminal hardware couldn't run the new integration client at all, forcing a hardware refresh plan the original scope hadn't budgeted for."),
    ('Arcadia Logistics — Fleet Analytics Rollout', 'Arcadia Logistics — Fleet Analytics Rollout — client engagement.', "Building a fleet telemetry and route-analytics platform for a logistics client, ingesting GPS and fuel-sensor data from several thousand vehicles to flag inefficient routing and maintenance risk. Includes a data-quality pass on the client's existing sensor feeds, which turned out noisier than the pilot suggested. The first version of the maintenance-risk model flagged too many false positives, prompting a retune before the client would trust it enough to act on."),
]


projects_table = sa.table(
    "projects",
    sa.column("name", sa.String),
    sa.column("description", sa.Text),
)


def upgrade() -> None:
    conn = op.get_bind()
    for name, old, new in DESCRIPTIONS:
        conn.execute(
            projects_table.update()
            .where(projects_table.c.name == name, projects_table.c.description == old)
            .values(description=new)
        )


def downgrade() -> None:
    conn = op.get_bind()
    for name, old, new in DESCRIPTIONS:
        conn.execute(
            projects_table.update()
            .where(projects_table.c.name == name, projects_table.c.description == new)
            .values(description=old)
        )
