"""initial schema

Revision ID: b01229e560ec
Revises: 
Create Date: 2026-08-04 12:04:14.684235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01229e560ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('fields_returned', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('offices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offices'))
    )
    op.create_table('org_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_units.id'], name=op.f('fk_org_units_parent_id_org_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_units'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('technical', 'language', 'domain', name='skillcategory', native_enum=False), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['skills.id'], name=op.f('fk_skills_canonical_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('directory_object_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('preferred_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('work_email', sa.String(length=320), nullable=False),
    sa.Column('work_phone', sa.String(length=50), nullable=True),
    sa.Column('slack_handle', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('employment_type', sa.Enum('fte', 'contractor', 'intern', name='employmenttype', native_enum=False), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('cost_centre', sa.String(length=50), nullable=True),
    sa.Column('personal_mobile', sa.String(length=50), nullable=True),
    sa.Column('availability_status', sa.Enum('available', 'away', 'restricted', name='availabilitystatus', native_enum=False), nullable=False),
    sa.Column('away_until', sa.Date(), nullable=True),
    sa.Column('delegate_id', sa.String(length=36), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['employees.id'], name=op.f('fk_employees_delegate_id_employees')),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], name=op.f('fk_employees_manager_id_employees')),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], name=op.f('fk_employees_office_id_offices')),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], name=op.f('fk_employees_org_unit_id_org_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('directory_object_id', name=op.f('uq_employees_directory_object_id')),
    sa.UniqueConstraint('work_email', name=op.f('uq_employees_work_email'))
    )
    op.create_table('employee_certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_certifications_employee_id_employees')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_employee_certifications_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_certifications'))
    )
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('learning', 'working', 'expert', name='skilllevel', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('inferred', 'self_reported', 'confirmed', 'certified', name='skillsource', native_enum=False), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_skills_employee_id_employees')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_employee_skills_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_skills')),
    sa.UniqueConstraint('employee_id', 'skill_id', name=op.f('uq_employee_skills_employee_id'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('project', 'system', 'function', 'policy', name='projecttype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owning_unit_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.Enum('public', 'internal', 'confidential', name='projectclassification', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], name=op.f('fk_projects_owner_id_employees')),
    sa.ForeignKeyConstraint(['owning_unit_id'], ['org_units.id'], name=op.f('fk_projects_owning_unit_id_org_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('employee_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_projects_employee_id_employees')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_employee_projects_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_projects'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_projects')
    op.drop_table('projects')
    op.drop_table('employee_skills')
    op.drop_table('employee_certifications')
    op.drop_table('employees')
    op.drop_table('skills')
    op.drop_table('org_units')
    op.drop_table('offices')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
