import type { CreateTicketInput } from "@/lib/tasks-repo"

/**
 * Presentation sample intake — written to Cosmos as origin "manual"
 * (not legacy seed). Balanced across the three Tasks decision lanes.
 */
export const DEMO_INTAKE_TICKETS: CreateTicketInput[] = [
  // ── Copilot can handle (auto) ─────────────────────────────────────
  {
    id: "IN-D9101",
    subject: "PTO carry-over — how many days can I bank?",
    requester: { name: "Dan Okafor", role: "Warehouse Associate", initials: "DO" },
    channel: "chat",
    clusterId: "leave-requests",
    topic: "Balance question · carry-over",
    urgency: "low",
    due: "3 days",
    disposition: "auto",
    state: "new",
    origin: "manual",
    snippet: "I've got 6 days left and won't use them before December. What's the carry-over cap?",
    suggestion: "Answer from leave policy and attach current balance — no approval needed.",
  },
  {
    id: "IN-D9102",
    subject: "Visa support letter for spouse application",
    requester: { name: "Aisha Karim", role: "Finance Analyst", initials: "AK" },
    channel: "email",
    clusterId: "verification-letters",
    topic: "Verification letter · immigration",
    urgency: "normal",
    due: "2 days",
    disposition: "auto",
    state: "new",
    origin: "manual",
    snippet: "Consulate wants confirmation of employment and salary on letterhead.",
    suggestion: "Standard template applies — generate and send without salary exception.",
  },
  {
    id: "IN-D9103",
    subject: "Benefit enrolment — adding spouse after marriage",
    requester: { name: "Luis Ferreira", role: "Solutions Architect", initials: "LF" },
    channel: "portal",
    clusterId: "payroll-questions",
    topic: "Benefits · qualifying life event",
    urgency: "normal",
    due: "5 days",
    disposition: "auto",
    state: "waiting",
    origin: "manual",
    snippet: "Adding spouse to medical plan, effective from wedding date. Certificate uploaded.",
    suggestion: "Qualifying-life-event playbook ready — proceed when certificate validates.",
  },
  {
    id: "IN-D9104",
    subject: "Employment dates for background check",
    requester: { name: "Northwind Talent", role: "External recruiter", initials: "NT" },
    channel: "email",
    clusterId: "verification-letters",
    topic: "Reference · dates only",
    urgency: "low",
    due: "3 days",
    disposition: "auto",
    state: "new",
    origin: "manual",
    snippet: "Confirming dates of employment for a candidate who left in 2024.",
    suggestion: "Dates-only response per policy — auto-send template.",
  },
  {
    id: "IN-D9105",
    subject: "W-2 reprint request for 2024",
    requester: { name: "Jordan Lee", role: "Customer Success", initials: "JL" },
    channel: "helpdesk",
    clusterId: "payroll-questions",
    topic: "Tax form · reprint",
    urgency: "normal",
    due: "2 days",
    disposition: "auto",
    state: "new",
    origin: "manual",
    snippet: "Need a PDF reprint of my 2024 W-2 for refinancing paperwork.",
    suggestion: "Pull from payroll archive and email securely — standard playbook.",
  },

  // ── Copilot drafted (assist) — middle lane ────────────────────────
  {
    id: "IN-D9201",
    subject: "Employment verification for mortgage lender",
    requester: { name: "Sarah Chen", role: "Senior Product Manager", initials: "SC" },
    channel: "helpdesk",
    clusterId: "verification-letters",
    topic: "Verification letter · includes salary",
    urgency: "normal",
    due: "Tomorrow 5pm",
    disposition: "assist",
    state: "triaged",
    origin: "manual",
    snippet:
      "Lender needs a letter confirming employment, title, start date and annual compensation.",
    suggestion: "Letter drafted from the employee record; salary disclosure needs your sign-off.",
  },
  {
    id: "IN-D9202",
    subject: "Offer accepted — Joe Marchetti, Product Designer",
    requester: { name: "Recruiting ATS", role: "System event", initials: "AT" },
    channel: "system",
    clusterId: "onboarding-starts",
    topic: "New starter · 1 Sep",
    urgency: "urgent",
    due: "Today 1pm",
    disposition: "assist",
    state: "triaged",
    origin: "manual",
    snippet: "Candidate accepted. Start date 2026-09-01. Onboarding packet ready to issue.",
    suggestion: "Packet complete — approve to send for e-signature.",
  },
  {
    id: "IN-D9203",
    subject: "6 missing punches — Seattle warehouse",
    requester: { name: "Time & Attendance", role: "System event", initials: "TA" },
    channel: "system",
    clusterId: "attendance-exceptions",
    topic: "Missing punches · pay period",
    urgency: "high",
    due: "Payroll cutoff 5pm",
    disposition: "assist",
    state: "triaged",
    origin: "manual",
    snippet: "Six exceptions flagged before payroll close. Five match badge access logs.",
    suggestion: "One shift needs manager attestation before corrections push to payroll.",
  },
  {
    id: "IN-D9204",
    subject: "Parental leave — expecting in November",
    requester: { name: "Amara Diallo", role: "Staff Engineer", initials: "AD" },
    channel: "portal",
    clusterId: "leave-requests",
    topic: "Parental leave · plan required",
    urgency: "normal",
    due: "This week",
    disposition: "assist",
    state: "new",
    origin: "manual",
    snippet: "Wanted to start paperwork early and understand the top-up policy.",
    suggestion: "Entitlement summary + draft leave plan ready for your review.",
  },
  {
    id: "IN-D9205",
    subject: "Deduction on August payslip I don't recognise",
    requester: { name: "Marcus Webb", role: "Account Executive", initials: "MW" },
    channel: "email",
    clusterId: "payroll-questions",
    topic: "Payslip discrepancy",
    urgency: "high",
    due: "Today",
    disposition: "assist",
    state: "new",
    origin: "manual",
    snippet: "There's a $180 line called 'BEN-ADJ' I've never seen before.",
    suggestion: "Reconciled against benefits change log — approve the draft reply with breakdown.",
  },
  {
    id: "IN-D9206",
    subject: "Welcome email + I-9 packet for new hire",
    requester: { name: "People Ops", role: "Onboarding", initials: "PO" },
    channel: "system",
    clusterId: "onboarding-starts",
    topic: "Day-one packet · send",
    urgency: "high",
    due: "Today",
    disposition: "assist",
    state: "waiting",
    origin: "manual",
    snippet: "I-9, NDA, and CoC generated for Maya Patel. Welcome email drafted with attachments.",
    suggestion: "Approve & Send the welcome email once you confirm the start date.",
  },

  // ── Needs your judgement (human) ──────────────────────────────────
  {
    id: "IN-D9301",
    subject: "Does the new remote policy apply to contractors?",
    requester: { name: "Priya Raman", role: "Engineering Manager", initials: "PR" },
    channel: "chat",
    clusterId: "policy-clarifications",
    topic: "Remote-work policy · scope",
    urgency: "normal",
    due: "2 days",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet: "Announcement says 'employees' — my team has four long-term contractors.",
    suggestion: "Policy is ambiguous. Decide once and Copilot will answer the other similar asks.",
  },
  {
    id: "IN-D9302",
    subject: "Which days count as core hours in the new policy?",
    requester: { name: "Tom Whitfield", role: "Support Lead", initials: "TW" },
    channel: "chat",
    clusterId: "policy-clarifications",
    topic: "Remote-work policy · core hours",
    urgency: "low",
    due: "2 days",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet: "Tuesday/Thursday anchor days were mentioned but the doc says three days.",
    suggestion: "Same root ambiguity as the contractor question — resolve together.",
  },
  {
    id: "IN-D9303",
    subject: "Relocating to Lisbon — what happens to my contract?",
    requester: { name: "Elena Ruiz", role: "Data Analyst", initials: "ER" },
    channel: "email",
    clusterId: "relocation-visa",
    topic: "Relocation · entity change",
    urgency: "high",
    due: "This week",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet: "Partner's job is moving us in October. Can I stay on the same team remotely?",
    suggestion: "No playbook yet. Several similar Lisbon requests this week — needs a policy call.",
  },
  {
    id: "IN-D9304",
    subject: "Work permit renewal — expires in 60 days",
    requester: { name: "Kenji Watanabe", role: "Security Engineer", initials: "KW" },
    channel: "form",
    clusterId: "relocation-visa",
    topic: "Work authorisation · renewal",
    urgency: "urgent",
    due: "Today",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet: "Immigration counsel needs an HR letter and the last 6 payslips.",
    suggestion: "Docs can be assembled; filing route and counsel choice need your call.",
  },
  {
    id: "IN-D9305",
    subject: "Confidential: concern about a manager's conduct",
    requester: { name: "Withheld", role: "Restricted", initials: "··" },
    channel: "form",
    clusterId: "employee-relations",
    topic: "Grievance · restricted handling",
    urgency: "urgent",
    due: "Today",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet: "Content hidden. Restricted-handling rule matched — Copilot did not read this.",
    suggestion: "Opened for you only. Nothing was indexed or auto-actioned.",
  },
  {
    id: "IN-D9306",
    subject: "Exception request — hire above band max",
    requester: { name: "Chris Nguyen", role: "VP Engineering", initials: "CN" },
    channel: "email",
    clusterId: "uncategorised",
    topic: "Compensation · band exception",
    urgency: "high",
    due: "Tomorrow",
    disposition: "human",
    state: "new",
    origin: "manual",
    snippet:
      "Offer for Staff Eng candidate needs 8% above band. Competing with two other firms.",
    suggestion: "No automation for band exceptions — Comp + HRBP decision required.",
  },
]
